import type { Metadata } from "next";
import { Figtree, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import ProgressClientProvider from "@/lib/providers/progress-client-provider";
import { TanstackProvider } from "@/lib/providers/tanstack-provider";

const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={figtree.variable}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ProgressClientProvider>
					<TanstackProvider>
						<Header />
						<main className="mx-auto mt-8 flex min-h-screen w-full max-w-4xl flex-1 flex-col px-4">
							{children}
						</main>
					</TanstackProvider>
				</ProgressClientProvider>
				<Toaster />
			</body>
		</html>
	);
}
